const expenseCategories = [
  {
    id: 1213,
    name: 'Grocery',
    tags: ['foods', 'vegetables', 'supermaeket', 'drinks', 'beverage'],
    budget: 420,
  },
  {
    id: 122341312,
    name: 'Hygiene',
    tags: ['detergent', 'shampoo', 'health care'],
    budget: 80,
  },
  {
    id: 234557,
    name: 'Sport',
    tags: ['gym', 'supplement', 'vitamins'],
    budget: 60,
  },
  {
    id: 457,
    name: 'Living cost',
    tags: ['rent', 'electricity', 'TV'],
    budget: 2200,
  },
  {
    id: 3457,
    name: 'Internt-Phone',
    tags: ['internet', 'phone'],
    budget: 60,
  },
  {
    id: 234123,
    name: 'Car-Transport',
    tags: ['gas', 'insurance', 'service', 'taxi', 'public transport'],
    budget: 250,
  },
  {
    id: 34545,
    name: 'Entertainment',
    tags: ['restaurant', 'bar'],
    budget: 200,
  },
  {
    id: 3545,
    name: 'Travel',
    tags: ['car trip'],
    budget: 100,
  },
  {
    id: 45,
    name: 'Benji',
    tags: ['food', 'vet', 'hyegine', 'tax'],
    budget: 90,
  },
  {
    id: 9867,
    name: 'Education',
    tags: ['foreign language', 'online course', 'driving license'],
    budget: 80,
  },
  {
    id: 866,
    name: 'Clothes',
    tags: ['fashion', 'shoes'],
    budget: 170,
  },
  {
    id: 12937,
    name: 'Home',
    tags: ['appliances', 'furniture', 'device'],
    budget: 100,
  },
  {
    id: 1238,
    name: 'Family',
    tags: ['souvenir', 'gift'],
    budget: 40,
  },
  {
    id: 2384767,
    name: 'Others',
    tags: ['friends gift', 'bank fees'],
    budget: 100,
  },
];

const expenses = [
  {
    id: 238467,
    category: 'Grocery',
    title: 'Edeka',
    amount: 85.12,
    date: '2023-12-12',
    forWho: 'Both',
    payment: "Nassim's Bank",
    comment: '',
  },
  {
    id: 234567,
    category: 'Grocery',
    title: 'Edeka',
    amount: 85.12,
    date: '2023-01-12',
    forWho: 'Nassim',
    payment: "Pooya's Bank",
    comment: "Friend's gift",
  },
  {
    id: 232267,
    category: 'Grocery',
    title: 'Edeka',
    amount: 85.12,
    date: '2023-01-12',
    forWho: 'Both',
    payment: "Pooya's Bank",
    comment: '',
  },
  {
    id: 2322267,
    category: 'Grocery',
    title: 'Edeka',
    amount: 385.12,
    date: '2024-01-12',
    forWho: 'Pooya',
    payment: "Pooya's Bank",
    comment: '',
  },
  {
    id: 23867,
    category: 'Grocery',
    title: 'Edeka',
    amount: 85.12,
    date: '2023-08-12',
    forWho: 'Nassim',
    payment: "Pooya's Bank",
  },
  {
    id: 238423767,
    category: 'Grocery',
    title: 'dm',
    amount: 85.12,
    date: '2023-12-06',
    forWho: 'Pooya',
    payment: "Pooya's Bank",
    comment: 'Sparkasse',
  },
  {
    id: 4767,
    category: 'Grocery',
    title: 'Kaufland',
    amount: 85.12,
    date: '2023-12-11',
    forWho: 'Pooya',
    payment: "Pooya's Bank",
    comment: 'Medicine',
  },
  {
    id: 23847,
    category: 'Car-Transport',
    title: 'Eurogida',
    amount: 85.12,
    date: '2023-12-06',
    forWho: 'Pooya',
    payment: "Nassim's Bank",
    comment: '',
  },
  {
    id: 284767,
    category: 'Grocery',
    title: 'Bolu',
    amount: 85.12,
    date: '2023-09-06',
    forWho: 'Both',
    payment: "Nassim's Bank",
    comment: '',
  },
  {
    id: 238476997,
    category: 'Education',
    title: 'Rossman',
    amount: 85.12,
    date: '2023-12-07',
    forWho: 'Both',
    payment: "Pooya's Bank",
    comment: 'Nothing',
  },
];

const expense = {
  category: 'Groceries',
  amount: 85.12,
  date: new Date(),
  who: 'Pooya',
};

export { expenseCategories, expenses };
